# Generated by Django 3.2 on 2025-11-05 12:00

import csv
import os
from django.db import migrations
from django.conf import settings

def load_initial_data(apps, schema_editor):
    Hanzi = apps.get_model('api', 'Hanzi')
    Pinyin = apps.get_model('api', 'Pinyin')
    Translation = apps.get_model('api', 'Translation')

    csv_path = os.path.join(settings.BASE_DIR, '..', 'data', 'tocfl_cleaned.csv')

    if not csv_path:
        raise FileNotFoundError("Could not find tocfl_cleaned.csv in data/ directory")

    def get(row, names, default=''):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return default

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            hanzi = get(row, ['traditional', 'character', 'hanzi']).strip()
            if not hanzi:
                continue
            zhuyin = get(row, ['zhuyin']).strip()
            topic = get(row, ['topic']).strip()
            level_raw = get(row, ['level']).strip()
            try:
                level = int(level_raw) if level_raw else 0
            except ValueError:
                level = 0
            pos = get(row, ['part of speech', 'pos']).strip()

            hanzi_obj = Hanzi.objects.create(
                hanzi=hanzi,
                zhuyin=zhuyin,
                topic=topic,
                level=level,
                pos=pos
            )

            p1 = get(row, ['pinyin_1', 'pinyin_x', 'pinyin1']).strip()
            p2 = get(row, ['pinyin_2', 'pinyin_y', 'pinyin2']).strip()
            if p1 or p2:
                Pinyin.objects.create(
                    hanzi=hanzi_obj,
                    pinyin1=p1,
                    pinyin2=p2
                )

            english = get(row, ['english']).strip()
            if english:
                if ';' in english:
                    chunks = english.split(';')
                else:
                    chunks = english.split(',')
                parts = [p.strip() for p in chunks]
                for trans in parts:
                    if trans:
                        Translation.objects.create(
                            hanzi=hanzi_obj,
                            translation=trans
                        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]