# Generated by Django 3.2 on 2025-11-05 14:00

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def populate_rounds(apps, schema_editor):
    Hanzi = apps.get_model('api', 'Hanzi')

    # Fetch all Hanzi entries ordered by level and id
    hanzi_entries = list(Hanzi.objects.order_by('level', 'id'))

    current_level = None
    current_round = 1
    count_in_round = 0

    for index, hanzi in enumerate(hanzi_entries):
        if hanzi.level != current_level:
            # Reset round when level changes
            current_level = hanzi.level
            count_in_round = 0

        print(f"Updating Hanzi {index + 1}: Level={hanzi.level}, Round={current_round}")
        hanzi.round = current_round
        hanzi.save()

        count_in_round += 1

        if count_in_round >= 20:
            current_round += 1
            count_in_round = 0


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RunPython(populate_rounds),
    ]
