# Generated by Django 5.1.3 on 2024-11-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pinyin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hanzi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='api.hanzi')),
            ],
        ),
    ]
